# GitHub Pages configuration
permalink: pretty
plugins:
  - jekyll-redirect-from

# 404 page handling
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# Custom 404 page
error_page: 404.html
